name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        yarn
        npm run-script build
      env:
        REACT_APP_OPEN_AI_API_KEY: ${{ secrets.REACT_APP_OPEN_AI_API_KEY }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build

permissions: read-all|write-all
